<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedInventory.Application\MedInventory.Application.csproj" />
    <ProjectReference Include="..\MedInventory.Domain\MedInventory.Domain.csproj" />
  </ItemGroup>

</Project>
